### ISSUE TITLE
macOS icon is m a s s i v e

### ISSUE THREAD

**Issue by grace-fagan** [emergenceland/memz#124]
![Screenshot 2023-03-25 at 5 00 35 PM](https://user-images.githubusercontent.com/95446735/227748025-e6854755-c3c7-4bd9-894a-7d24fca3d8c3.png)
### Current state of the issue: 
According to ChatGPT:
![Screenshot 2023-03-25 at 5 32 20 PM](https://user-images.githubusercontent.com/95446735/227748845-021afd26-57f9-4e38-8658-d341a768d18d.png)

Below is the src icon for `sizes: "512x512"`
<img src="https://user-images.githubusercontent.com/95446735/227748446-0a121026-e54f-4bf8-af29-7650de7f9796.png" width=100>

When there is only 1 icon size in the manifest (512x512), macOS pulls that icon. However, when there are multiple sizes in the `icons` array, the specified 512x512 icon does not appear to be used.

**Comment by cha0sg0d** [comment]
PWA GO AWAY
