### ISSUE TITLE
Deferred Deep Linking

### ISSUE THREAD

**Issue by grace-fagan** [emergenceland/memz#263]
- [x] Figma user flow

Implementation plan:

- [x] If user opens website without app installed, prompt user to download the app
- [x] If user clicks download app, copy the game link to their clipboard
- [x] On app open, if game link in clipboard, ask user for permission to paste the game link

Additional cases:
- [ ] How to link to app in discord / FB messenger

**Comment by cha0sg0d** [comment]
Will be handled by #288

**Comment by grace-fagan** [comment]
Closed by #288
